# Generated by Django 3.1.1 on 2020-10-20 22:36

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='member_content',
            field=django_quill.fields.QuillField(default='content'),
            preserve_default=False,
        ),
    ]
