# Generated by Django 3.0.7 on 2020-07-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bonus',
            field=models.TextField(null=True),
        ),
    ]
