# Generated by Django 3.0.7 on 2020-07-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bonus_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
