# Generated by Django 3.1.1 on 2020-10-30 17:33

from django.db import migrations, models
import django.utils.timezone
import django_quill.fields
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200714_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published',)},
        ),
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='post',
            name='bonus_title',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=django_quill.fields.QuillField(default='random text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='member_content',
            field=django_quill.fields.QuillField(default='member content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='preview_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/tutorials/'),
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('P', 'Published'), ('D', 'Draft')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
