# Generated by Django 3.1.1 on 2020-11-30 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_transfer_body_and_bonus_to_content_and_member_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='bonus',
        ),
    ]
