# Generated by Django 3.1.1 on 2020-12-04 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_moveToHTML'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='post',
            name='bonus_title',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
