# Generated by Django 3.1.1 on 2020-12-15 18:14

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20201204_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='member_content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
