# Generated by Django 2.2.4 on 2019-08-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zappyuser',
            name='active_membership',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zappyuser',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zappyuser',
            name='stripe_id',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zappyuser',
            name='stripe_subscription_id',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
