# Generated by Django 3.0.7 on 2020-07-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewide', '0002_auto_20190829_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='zappyuser',
            name='pic',
            field=models.ImageField(null=True, upload_to='sitewide/user_pics'),
        ),
    ]
