# Generated by Django 3.0.7 on 2020-07-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewide', '0004_auto_20200716_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zappyuser',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='sitewide/user_pics'),
        ),
    ]
