# Generated by Django 3.0.7 on 2020-07-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewide', '0005_auto_20200718_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastCommit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_url', models.URLField()),
                ('commit_time', models.DateTimeField()),
                ('last_checked', models.DateTimeField()),
            ],
        ),
    ]
