# Generated by Django 3.0.7 on 2020-07-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewide', '0006_lastcommit'),
    ]

    operations = [
        migrations.AddField(
            model_name='zappyuser',
            name='apple_receipt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
