# Generated by Django 3.1.5 on 2021-02-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewide', '0008_auto_20200903_0442'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('_type', models.CharField(choices=[('m', 'Monthly'), ('y', 'Yearly')], max_length=1)),
                ('amount', models.PositiveIntegerField()),
                ('plan', models.CharField(help_text='no plan_ prefix is required.', max_length=16)),
            ],
            options={
                'ordering': ('_type', 'amount'),
            },
        ),
    ]
