# Generated by Django 3.0.3 on 2020-02-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('expenses', models.DecimalField(decimal_places=10, max_digits=10)),
                ('revenue', models.DecimalField(decimal_places=10, max_digits=10)),
                ('description', models.TextField()),
            ],
        ),
    ]
