# Generated by Django 3.0.3 on 2020-02-19 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_auto_20200219_0339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='month',
            old_name='description',
            new_name='body',
        ),
    ]
