# Generated by Django 3.0.3 on 2020-02-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_auto_20200219_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='youtube_id',
            field=models.TextField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
