# Generated by Django 3.0.3 on 2020-02-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_month_youtube_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='youtube_id',
            field=models.CharField(max_length=255),
        ),
    ]
