# Generated by Django 3.0.7 on 2020-07-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_auto_20200219_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
