# Generated by Django 2.2.7 on 2019-12-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_lecture_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
