# Generated by Django 2.2.7 on 2019-12-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lecture_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='vimeo_video_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
