# Generated by Django 2.2.7 on 2020-01-10 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20191220_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='first_lecture',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Lecture'),
            preserve_default=False,
        ),
    ]
