# Generated by Django 3.0.3 on 2020-05-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_first_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='preview',
            field=models.BooleanField(default=False),
        ),
    ]
