# Generated by Django 3.0.3 on 2020-06-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lecture_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='download_link',
            field=models.URLField(blank=True),
        ),
    ]
