# Generated by Django 3.0 on 2020-07-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lecture_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='download_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
    ]
