# Generated by Django 3.0 on 2020-08-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
