# Generated by Django 3.0 on 2020-08-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_lecture_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='download_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
