# Generated by Django 3.1.1 on 2020-10-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20200919_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
