# Generated by Django 3.1.1 on 2020-11-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_youtube_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='promo_download_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
