# Generated by Django 3.1.5 on 2021-03-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_promo_download_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_video_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
