# Generated by Django 3.1.8 on 2022-06-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_userhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='download_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
