# Generated by Django 3.0.6 on 2020-06-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('starting_code', models.TextField(blank=True, null=True)),
                ('answer_code', models.TextField()),
            ],
        ),
    ]
