# Generated by Django 3.1.5 on 2021-05-25 09:53

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialpage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('code', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(choices=[('python', 'Python'), ('swift', 'Swift'), ('json', 'JSON'), ('css', 'CSS'), ('html', 'HTML'), ('javascript', 'JavaScript'), ('kotlin', 'Kotlin'), ('java', 'Java')], help_text='Coding language', identifier='language', label='Language')), ('code', wagtail.core.blocks.TextBlock(identifier='code', label='Code'))], default_language='python', label='Code')), ('video', wagtail.core.blocks.StructBlock([('video', wagtail.core.blocks.CharBlock())]))]),
        ),
    ]
