# Generated by Django 3.1.5 on 2021-05-28 08:55

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('tutorials', '0002_auto_20210525_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialpage',
            name='promo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='tutorialpage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'h5', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'code', 'superscript', 'subscript', 'strikethrough', 'blockquote'])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('code', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(choices=[('python', 'Python'), ('swift', 'Swift'), ('json', 'JSON'), ('css', 'CSS'), ('html', 'HTML'), ('javascript', 'JavaScript'), ('kotlin', 'Kotlin'), ('java', 'Java')], help_text='Coding language', identifier='language', label='Language')), ('code', wagtail.core.blocks.TextBlock(identifier='code', label='Code'))], default_language='python', label='Code')), ('video', wagtail.core.blocks.StructBlock([('video', wagtail.core.blocks.CharBlock(label='YouTube ID'))]))]),
        ),
    ]
